**Part A**

**Load Data**

In [ ]:
# import necessary libraries
 
import pandas as pd
 
df = pd.read_csv('/content/drive/MyDrive/tree/Agaricus-lepiota.data.txt', header=None)
df
 
#  Specify Column Names (Features) 
 
df.columns = ["class", "cap-shape", "cap-surface", "cap-color", "bruises",
             "odor", "gill-attachment", "gill-spacing", "gill-size",
             "gill-color", "stalk-shape", "stalk-root",
             "stalk-surface-above-ring",
             "stalk-surface-below-ring",
             "stalk-color-above-ring",
             "stalk-color-below-ring",
             "veil-type", "veil-color", "ring-number", "ring-type",
             "spore-print-color", "population", "habitat" ]
 
df

     class cap-shape cap-surface  ... spore-print-color population habitat
0        p         x           s  ...                 k          s       u
1        e         x           s  ...                 n          n       g
2        e         b           s  ...                 n          n       m
3        p         x           y  ...                 k          s       u
4        e         x           s  ...                 n          a       g
...    ...       ...         ...  ...               ...        ...     ...
8119     e         k           s  ...                 b          c       l
8120     e         x           s  ...                 b          v       l
8121     e         f           s  ...                 b          c       l
8122     p         k           y  ...                 w          v       l
8123     e         x           s  ...                 o          c       l

[8124 rows x 23 columns]

Missing Values

In [ ]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [ ]:
 df.isnull().any() # This code shows that there is a column contains a null value or not, as you can see below the dataset has a columns contains "nan" value.
# So, this code returns true for stalk-root column.

class                       False
cap-shape                   False
cap-surface                 False
cap-color                   False
bruises                     False
odor                        False
gill-attachment             False
gill-spacing                False
gill-size                   False
gill-color                  False
stalk-shape                 False
stalk-root                  False
stalk-surface-above-ring    False
stalk-surface-below-ring    False
stalk-color-above-ring      False
stalk-color-below-ring      False
veil-type                   False
veil-color                  False
ring-number                 False
ring-type                   False
spore-print-color           False
population                  False
habitat                     False
dtype: bool

In [ ]:
 # Also, we can write a simple for loop to see column(s) which contains(s) non-sense or null value(s).
 
for i in df.columns:
    print(i,df[i].unique())

class ['p' 'e']
cap-shape ['x' 'b' 's' 'f' 'k' 'c']
cap-surface ['s' 'y' 'f' 'g']
cap-color ['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']
bruises ['t' 'f']
odor ['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']
gill-attachment ['f' 'a']
gill-spacing ['c' 'w']
gill-size ['n' 'b']
gill-color ['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']
stalk-shape ['e' 't']
stalk-root ['e' 'c' 'b' 'r' '?']
stalk-surface-above-ring ['s' 'f' 'k' 'y']
stalk-surface-below-ring ['s' 'f' 'y' 'k']
stalk-color-above-ring ['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']
stalk-color-below-ring ['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']
veil-type ['p']
veil-color ['w' 'n' 'o' 'y']
ring-number ['o' 't' 'n']
ring-type ['p' 'e' 'l' 'f' 'n']
spore-print-color ['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']
population ['s' 'n' 'a' 'v' 'y' 'c']
habitat ['u' 'g' 'm' 'd' 'p' 'w' 'l']

 as you can see 'stalk-root' contains '?' value which is non-sense. We need to fill it with reasonable value instead of '?'. There are several ways to fill missing or non-sense data.This method is very dummy, but sometimes it may be working well suprisingly. The column(s) contain(s) missing or non-sense value(s) can be wiped out. </br>If the column contains missing or non-sense value is categorical, then we can fill the missing or non-sense values with value has most frequency in that column. If the column is numerical, then we can fill the missing or non-sense values with average or median value of that column. </br>We can built decision tree or regression model for missing or non-sense value(s).

In [ ]:
 df['stalk-root'].value_counts()

b    3776
?    2480
e    1120
c     556
r     192
Name: stalk-root, dtype: int64

For edible class

In [ ]:
temp = df.loc[df['class'] == 'e' ]
temp['stalk-root'].value_counts()

b    1920
e     864
?     720
c     512
r     192
Name: stalk-root, dtype: int64

For poisonous class

In [ ]:
temp = df.loc[df['class'] == 'p' ]
temp['stalk-root'].value_counts()

b    1856
?    1760
e     256
c      44
Name: stalk-root, dtype: int64

In [ ]:
df['stalk-root'] = df['stalk-root'].replace('?','b') # '?' in stalk-root attribute filled with 'b' has most frequency.
# Let's see whether non-sense data exists, or not.
df['stalk-root'].value_counts()

b    6256
e    1120
c     556
r     192
Name: stalk-root, dtype: int64

In [ ]:
temp = df.drop('class', axis=1)
temp['class']= df['class']
df = temp
df

     cap-shape cap-surface cap-color  ... population habitat class
0            x           s         n  ...          s       u     p
1            x           s         y  ...          n       g     e
2            b           s         w  ...          n       m     e
3            x           y         w  ...          s       u     p
4            x           s         g  ...          a       g     e
...        ...         ...       ...  ...        ...     ...   ...
8119         k           s         n  ...          c       l     e
8120         x           s         n  ...          v       l     e
8121         f           s         n  ...          c       l     e
8122         k           y         n  ...          v       l     p
8123         x           s         n  ...          c       l     e

[8124 rows x 23 columns]

In [ ]:
print('Number of samples: ', df.shape[0])
print('Number of attributes: ', df.shape[1])
 
value_counts = df['class'].value_counts()
e = value_counts['e']
p = value_counts['p']
 
print('\nEdible:    ', e)
print('Poisonous: ', p)
print('\nTotal:     ', e + p)

Number of samples:  8124
Number of attributes:  23

Edible:     4208
Poisonous:  3916

Total:      8124


**ID3 Algorithm**

**In the ID3 algorithm, decision trees are** **calculated using the concept of entropy and** **information gain.**
**Entropy can be defined as:**
**H(S)=−∑i=1Npilog2pi **

In [ ]:
import pandas as pd
import numpy as np
 
# eps for making value a bit greater than 0 later on
eps = np.finfo(float).eps
 
from numpy import log2 as log

In [ ]:
def find_entropy(df):
    '''
    Function to calculate the entropy of the label class
    '''
    Class = df.keys()[-1] 
    entropy = 0
    values = df[Class].unique()
    for value in values:
        fraction = df[Class].value_counts()[value]/len(df[Class])
        entropy += -fraction*np.log2(fraction)
    return entropy

In [ ]:
def find_entropy_attribute(df,attribute):
    '''
    Function to calculate the entropy of all features.
    '''
    Class = df.keys()[-1]   
    target_variables = df[Class].unique()  
    variables = df[attribute].unique()
    entropy2 = 0
    for variable in variables:
        entropy = 0
        for target_variable in target_variables:
                num = len(df[attribute][df[attribute]==variable][df[Class] ==target_variable])
                den = len(df[attribute][df[attribute]==variable])
                fraction = num/(den+eps)
                entropy += -fraction*log(fraction+eps)
        fraction2 = den/len(df)
        entropy2 += -fraction2*entropy
    return abs(entropy2)

In [ ]:
 
 
def find_winner(df):
    '''
    Function to find the feature with the highest information gain.
    '''
    Entropy_att = []
    IG = []
    for key in df.keys()[:-1]:
#         Entropy_att.append(find_entropy_attribute(df,key))
        IG.append(find_entropy(df)-find_entropy_attribute(df,key))
    return df.keys()[:-1][np.argmax(IG)]

In [ ]:
 
 
def get_subtable(df, node, value):
    '''
    Function to get a subtable of met conditions.
    
    node: Column name
    value: Unique value of the column
    '''
    return df[df[node] == value].reset_index(drop=True)

In [ ]:
def buildTree(df,tree=None): 
    '''
    Function to build the ID3 Decision Tree.
    '''
    Class = df.keys()[-1]  
    #Here we build our decision tree
 
    #Get attribute with maximum information gain
    node = find_winner(df)
    
    #Get distinct value of that attribute e.g Salary is node and Low,Med and High are values
    attValue = np.unique(df[node])
    
    #Create an empty dictionary to create tree    
    if tree is None:                    
        tree={}
        tree[node] = {}
    
   #We make loop to construct a tree by calling this function recursively. 
    #In this we check if the subset is pure and stops if it is pure. 
 
    for value in attValue:
        
        subtable = get_subtable(df,node,value)
        clValue,counts = np.unique(subtable['class'],return_counts=True)                        
        
        if len(counts)==1:#Checking purity of subset
            tree[node][value] = clValue[0]                                                    
        else:        
            tree[node][value] = buildTree(subtable) #Calling the function recursively 
                   
    return tree

In [ ]:
def predict(inst,tree):
    '''
    Function to predict for any input variable.
    '''
    #Recursively we go through the tree that we built earlier
 
    for nodes in tree.keys():  
        
        value = inst[nodes]
        tree = tree[nodes][value]
        prediction = 0
            
        if type(tree) is dict:
            prediction = predict(inst, tree)
        else:
            prediction = tree
            break;                            
        
    return prediction

 Data Transformation
 
Our dataset is full of categorical data. We need to convert these categorical values into numerical representatives. There are two ways to do this.
Label Encoding: This method can be perform on columns with binary values. We can't apply this method on a columns has more than two different values, because this method may cause a hierarchy between values in a column. So, this may cause incorrect classification.
 
One-Hot Encoding: This method can also be called "Dummy Variable" by some. In this method, each distinct values in a column transform into a column. Unlike label encoding, there is no trouble in terms of hierarchy. As dataset grows dimensionally, this method may cause low running performance.

In [ ]:
 
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for col in df.columns:
    df[col] = labelencoder.fit_transform(df[col])
 
df.head()

   cap-shape  cap-surface  cap-color  ...  population  habitat  class
0          5            2          4  ...           3        5      1
1          5            2          9  ...           2        1      0
2          0            2          8  ...           2        3      0
3          5            3          8  ...           3        5      1
4          5            2          3  ...           0        1      0

[5 rows x 23 columns]

**10 Fold Cross Validation**

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
 
 
kf = KFold(n_splits=10)
 
X = df
y = df['class']
 
accuracy_list = []
 
for train_index, test_index in kf.split(X):
  #  print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X.iloc[train_index], X.iloc[test_index]
   X_test.drop('class', axis=1)
   y_train, y_test = y.iloc[train_index], y.iloc[test_index]
   tree = buildTree(X_train)
   
   y_pred=[]
   for i in range(len(X_test)):
     inst = pd.Series(X_test.iloc[i])
     prediction = predict(inst, tree)
     y_pred.append(prediction)
   accuracy =  accuracy_score(y_test, y_pred)
   accuracy_list.append(accuracy)
   report = classification_report(y_test, y_pred)
   print('Fold Number:', len(accuracy_list))  
   print('Accuracy Score:', accuracy)
   print('Classification Report:', '\n', report)  
   print(100 * '=')
 
print('\n')
print('Final Accuracy', np.mean(accuracy_list))
print('Standard Deviation', np.std(accuracy_list))
print('\n')
print(100 * '=')

Fold Number: 1
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       729
           1       1.00      1.00      1.00        84

    accuracy                           1.00       813
   macro avg       1.00      1.00      1.00       813
weighted avg       1.00      1.00      1.00       813

====================================================================================================
Fold Number: 2
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       703
           1       1.00      1.00      1.00       110

    accuracy                           1.00       813
   macro avg       1.00      1.00      1.00       813
weighted avg       1.00      1.00      1.00       813

====================================================================================================
Fold Number: 3
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       745
           1       1.00      1.00      1.00        68

    accuracy                           1.00       813
   macro avg       1.00      1.00      1.00       813
weighted avg       1.00      1.00      1.00       813

====================================================================================================
Fold Number: 4
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       697
           1       1.00      1.00      1.00       116

    accuracy                           1.00       813
   macro avg       1.00      1.00      1.00       813
weighted avg       1.00      1.00      1.00       813

====================================================================================================
Fold Number: 5
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       453
           1       1.00      1.00      1.00       359

    accuracy                           1.00       812
   macro avg       1.00      1.00      1.00       812
weighted avg       1.00      1.00      1.00       812

====================================================================================================
Fold Number: 6
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        98
           1       1.00      1.00      1.00       714

    accuracy                           1.00       812
   macro avg       1.00      1.00      1.00       812
weighted avg       1.00      1.00      1.00       812

====================================================================================================
Fold Number: 7
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       175
           1       1.00      1.00      1.00       637

    accuracy                           1.00       812
   macro avg       1.00      1.00      1.00       812
weighted avg       1.00      1.00      1.00       812

====================================================================================================
Fold Number: 8
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       101
           1       1.00      1.00      1.00       711

    accuracy                           1.00       812
   macro avg       1.00      1.00      1.00       812
weighted avg       1.00      1.00      1.00       812

====================================================================================================
Fold Number: 9
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       664

    accuracy                           1.00       812
   macro avg       1.00      1.00      1.00       812
weighted avg       1.00      1.00      1.00       812

====================================================================================================
Fold Number: 10
Accuracy Score: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       359
           1       1.00      1.00      1.00       453

    accuracy                           1.00       812
   macro avg       1.00      1.00      1.00       812
weighted avg       1.00      1.00      1.00       812

====================================================================================================


Final Accuracy 1.0
Standard Deviation 0.0


====================================================================================================